### PR TITLE
Fixes checkboxselectmultiple and radioselect repeats form's attributes #16

### LINKED ISSUE #16: checkboxselectmultiple and radioselect repeats form's attributes
Hi,

Thank you for this excellent project!
I discovered this bug in the templates; please check it out.

## Reproduction code

```python
from django import forms

class DemoForm(forms.Form):
    language = forms.MultipleChoiceField(
        choices=[
            ("cpp", "C++"),
            ("py", "Python"),
            ("js", "JavaScript"),
        ],
        widget=forms.CheckboxSelectMultiple(),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = "FORM_ID"
        self.helper.form_class = "FORM_CLASS"
        self.helper.attrs["ATTR"] = "VALUE"
```

## Actual vs expected output

```diff
<form ATTR="VALUE" class="FORM_CLASS" id="FORM_ID" method="post">
  <div id="div_id_language" class="form-group">
    <label>Language</label>
-    <div ATTR="VALUE" class="FORM_CLASS" id="FORM_ID">
+    <div>
      <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" name="language" value="cpp" id="id_language_0">
        <label class="custom-control-label" for="id_language_0">C++</label>
      </div>
      <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" name="language" value="py" id="id_language_1">
        <label class="custom-control-label" for="id_language_1">Python</label>
      </div>
      <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" name="language" value="js" id="id_language_2">
        <label class="custom-control-label" for="id_language_2">JavaScript</label>
      </div>
    </div>
  </div>
</form>
```

As you can see, `<form>`'s attributes are inherited by the `<div>`.

I could trace this problem back to this line:

https://github.com/django-crispy-forms/crispy-bootstrap4/blob/f25758822da29cf5b1e1d96694bb651e93b8ff23/crispy_bootstrap4/templates/bootstrap4/layout/checkboxselectmultiple.html#L4

I think it should be `field.flat_attrs` instead of `flat_attrs`, but I'm not familiar enough with this project to be sure.

As far as I could tell, only two templates are affected [checkboxselectmultiple.html](https://github.com/django-crispy-forms/crispy-bootstrap4/blob/f25758822da29cf5b1e1d96694bb651e93b8ff23/crispy_bootstrap4/templates/bootstrap4/layout/checkboxselectmultiple.html#L4) and [radioselect.html](https://github.com/django-crispy-forms/crispy-bootstrap4/blob/f25758822da29cf5b1e1d96694bb651e93b8ff23/crispy_bootstrap4/templates/bootstrap4/layout/radioselect.html#L4)

Best regards,
Benoit

### PR DESCRIPTION
**Pull request by smithdc1**
Fixes #16

### CODE REVIEW

**Comment by smithdc1** [comment]
@bblanchon & @glenvaughan does this work for you?

**Comment by bblanchon** [comment]
Thanks, @smithdc1; this change does fix #16.
However, it introduces a regression: we can no longer add custom attributes to this `<div>`.

For example:

```python
from django import forms

class DemoForm(forms.Form):
    language = forms.MultipleChoiceField(
        choices=[
            ("cpp", "C++"),
            ("py", "Python"),
            ("js", "JavaScript"),
        ],
        widget=forms.CheckboxSelectMultiple(),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Field("language", style="background: grey"),
        )
```

Actual vs expected output:

```diff
<form method="post">
  <div id="div_id_language" class="form-group">
    <label>Language</label>
-    <div>
+    <div style="background: grey">
     <div class="custom-control custom-checkbox">
       <input type="checkbox" class="custom-control-input" name="language" value="cpp" id="id_language_0">
       <label class="custom-control-label" for="id_language_0">C++</label>
     </div>
     <div class="custom-control custom-checkbox">
       <input type="checkbox" class="custom-control-input" name="language" value="py" id="id_language_1">
       <label class="custom-control-label" for="id_language_1">Python</label>
     </div>
     <div class="custom-control custom-checkbox">
       <input type="checkbox" class="custom-control-input" name="language" value="js" id="id_language_2">
       <label class="custom-control-label" for="id_language_2">JavaScript</label>
     </div>
   </div>
  </div>
</form>
```

**Comment by smithdc1** [comment]
In your example, I'm surprised that `style="background: grey"` doesn't also feature on the `<input>`?

``` html
<form method="post">
    <div id="div_id_language" class="form-group">
        <label class="requiredField"> Language<span class="asteriskField">*</span> </label>
        <div style="background: grey">
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="language" value="cpp" style="background: grey" id="id_language_0" /> <label class="custom-control-label" for="id_language_0"> C++ </label>
            </div>
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="language" value="py" style="background: grey" id="id_language_1" /> <label class="custom-control-label" for="id_language_1"> Python </label>
            </div>
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="language" value="js" style="background: grey" id="id_language_2" /> <label class="custom-control-label" for="id_language_2"> JavaScript </label>
            </div>
        </div>
    </div>
</form>

```

I expect that additional kwargs for `Field` are only added to widgets / `<input>`.

**Comment by bblanchon** [comment]
You're right.
I didn't notice, but these attributes also apply to the checkboxes.

But is this the correct behavior, because it seems inconsistent with the other controls?
For example, field attributes apply to the `<select multiple>` element, not each `<option>`.
Why would checkbox-select-multiple behave differently since it's supposed to be a drop-in replacement for `<select multiple>`?

**Comment by smithdc1** [comment]
Interesting question. I always like to ask WWDJ (what would Django do) in cases like this. It's likely that crispy-forms is using django's own templates at this level. 

I think this is the expected behavior. Looking at bootstrap's docs it's also the `<select multiple>` and `<input>` tags that are targeted for classes rather than `<options>`. It seems to me that styling `<options>` isn't that well supported. See this 12 year old ticket for django/django [Ticket #16149](https://code.djangoproject.com/ticket/16149).

Form Code

<details>

``` python
    class DemoForm(forms.Form):
        language = forms.MultipleChoiceField(
            choices=[
                ("cpp", "C++"),
                ("py", "Python"),
                ("js", "JavaScript"),
            ],
            widget=forms.SelectMultiple(attrs={"style": "background: grey"}),
        )
        language2 = forms.MultipleChoiceField(
            choices=[
                ("cpp", "C++"),
                ("py", "Python"),
                ("js", "JavaScript"),
            ],
            widget=forms.CheckboxSelectMultiple(attrs={"style": "background: grey"}),
        )
    form = DemoForm()
    form.helper = FormHelper()
    form.helper.layout = Layout(
        "language",
        "language2"
    )

```

</details>


HTML Output
<details>



``` html
<form method="post">
    <div id="div_id_language" class="form-group">
        <label for="id_language" class="requiredField"> Language<span class="asteriskField">*</span> </label>
        <div>
            <select name="language" style="background: grey;" class="selectmultiple custom-select" required id="id_language" multiple>
                <option value="cpp">C++</option>
                <option value="py">Python</option>
                <option value="js">JavaScript</option>
            </select>
        </div>
    </div>
    <div id="div_id_language2" class="form-group">
        <label class="requiredField"> Language2<span class="asteriskField">*</span> </label>
        <div>
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="language2" value="cpp" style="background: grey;" id="id_language2_0" /> <label class="custom-control-label" for="id_language2_0"> C++ </label>
            </div>
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="language2" value="py" style="background: grey;" id="id_language2_1" /> <label class="custom-control-label" for="id_language2_1"> Python </label>
            </div>
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="language2" value="js" style="background: grey;" id="id_language2_2" /> <label class="custom-control-label" for="id_language2_2"> JavaScript </label>
            </div>
        </div>
    </div>
</form>



```

</details>

I wonder if we're going a bit off track -- what's your requirement here, is it to add css classes to this`<div>` in the template?

**Comment by bblanchon** [comment]
I understand; it makes sense to follow Django's behavior.

My goal is to add classes `form-control h-auto` to this `<div>` so that it looks like other controls and a `max-height` style because it's getting too tall.
But that's not a problem; I'll override this template in my project.

**Pull request merged**
